# SQL Murder Mystery

- There's been a Murder in SQL City! The SQL Murder Mystery is designed to be both a self-directed lesson to learn SQL concepts and commands and a fun game for experienced SQL users to solve an intriguing crime.
- A crime has taken place and the detective needs your help. The detective gave you the crime scene report, but you somehow lost it. You vaguely remember that the crime was a ​murder​ that occurred sometime on ​Jan.15, 2018,​ and that it took place in ​SQL City​.
- Start by retrieving the corresponding crime scene report from the police department’s database.


In [1]:
import numpy as np
import pandas as pd
import requests
import sqlite3        # For Handling database

In [2]:
#Setting connection with database
url = "https://raw.githubusercontent.com/rajvalvi/Prepinsta-Winter-Internship-in-Data-Analytics/main/week-5/sql-murder-mystery.db"
r = requests.get(url, allow_redirects=True)
open('sql-murder-mystery.db', 'wb').write(r.content)
conn = sqlite3.connect('sql-murder-mystery.db')

In [3]:
#cheking connection
print(conn)

In [4]:
#All tables in sql-murder-mystery database
show_tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
print(show_tables)

                     name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution


In [5]:
pd.set_option('display.max_colwidth', None)

In [7]:
# watching all the tables from the database

In [6]:
crime_scene_report=pd.read_sql_query("SELECT * FROM crime_scene_report;",conn)
crime_scene_report.head()

date     type                                              description  \
0  20180115  robbery        A Man Dressed as Spider-Man Is on a Robbery Spree   
1  20180115   murder                        Life? Dont talk to me about life.   
2  20180115   murder      Mama, I killed a man, put a gun against his head...   
3  20180215   murder                               REDACTED REDACTED REDACTED   
4  20180215   murder  Someone killed the guard! He took an arrow to the knee!   

       city  
0       NYC  
1    Albany  
2      Reno  
3  SQL City  
4  SQL City

In [8]:
drivers_license = pd.read_sql_query("SELECT * FROM drivers_license", conn)
drivers_license.head()

id  age  height eye_color hair_color  gender plate_number  car_make  \
0  100280   72      57     brown        red    male       P24L4U     Acura   
1  100460   63      72     brown      brown  female       XF02T6  Cadillac   
2  101029   62      74     green      green  female       VKY5KR     Scion   
3  101198   43      54     amber      brown  female       Y5NZ08    Nissan   
4  101255   18      79      blue       grey  female       5162Z1     Lexus   

  car_model  
0       MDX  
1       SRX  
2        xB  
3     Rogue  
4        GS

In [9]:
person= pd.read_sql_query("SELECT * FROM person",conn)
person.head()

id                 name  license_id  address_number address_street_name  \
0  10000   Christoper Peteuil      993845             624        Bankhall Ave   
1  10007  Kourtney Calderwood      861794            2791       Gustavus Blvd   
2  10010            Muoi Cary      385336             741     Northwestern Dr   
3  10016          Era Moselle      431897            1987       Wood Glade St   
4  10025         Trena Hornby      550890             276       Daws Hill Way   

         ssn  
0  747714076  
1  477972044  
2  828638512  
3  614621061  
4  223877684

In [10]:
facebook_event_checkin= pd.read_sql_query("SELECT * FROM facebook_event_checkin",conn)
facebook_event_checkin.head()

person_id  event_id  \
0      28508      5880   
1      63713      3865   
2      63713      3999   
3      63713      6436   
4      82998      4470   

                                                            event_name  \
0                      Nudists are people who wear one-button suits.\n   
1  but that's because it's the best book on anything for the layman.\n   
2                             If Murphy's Law can go wrong, it will.\n   
3     Old programmers never die.  They just branch to a new address.\n   
4                                 Help a swallow land at Capistrano.\n   

       date  
0  20170913  
1  20171009  
2  20170502  
3  20170926  
4  20171022

In [11]:
interview= pd.read_sql_query("SELECT * FROM interview",conn)
interview.head()

person_id  \
0      28508   
1      63713   
2      86208   
3      35267   
4      33856   

                                                                transcript  
0                                      ‘I deny it!’ said the March Hare.\n  
1                                                                       \n  
2                            way, and the whole party swam to the shore.\n  
3  lessons in here? Why, there’s hardly room for YOU, and no room at all\n  
4                                                                       \n

In [12]:
get_fit_now_member= pd.read_sql_query("SELECT * FROM get_fit_now_member",conn)
get_fit_now_member.head()

id  person_id                name  membership_start_date  \
0  NL318      65076     Everette Koepke               20170926   
1  AOE21      39426        Noe Locascio               20171005   
2  2PN28      63823  Jeromy Heitschmidt               20180215   
3  0YJ24      80651      Waneta Wellard               20171206   
4  3A08L      32858        Mei Bianchin               20170401   

  membership_status  
0              gold  
1           regular  
2            silver  
3              gold  
4            silver

In [13]:
get_fit_now_check_in= pd.read_sql_query("SELECT * FROM get_fit_now_check_in",conn)
get_fit_now_check_in.head()

membership_id  check_in_date  check_in_time  check_out_time
0         NL318       20180212            329             365
1         NL318       20170811            469             920
2         NL318       20180429            506             554
3         NL318       20180128            124             759
4         NL318       20171027            418            1019

In [14]:
income= pd.read_sql_query("SELECT * FROM income",conn)
income.head()

ssn  annual_income
0  100009868          52200
1  100169584          64500
2  100300433          74400
3  100355733          35900
4  100366269          73000

In [15]:
solution= pd.read_sql_query("SELECT * FROM solution",conn)
solution.head()

Empty DataFrame
Columns: [user, value]
Index: []

Retrieve Crime Scene Report and check the date Jan.15, 2018, in SQL City.



In [16]:
crime_scene_report=pd.read_sql_query('''SELECT * FROM crime_scene_report
                                    WHERE date=20180115 and
                                    type='murder' and
                                    city='SQL City';''',conn)
crime_scene_report

date    type  \
0  20180115  murder   

                                                                                                                                                                                 description  \
0  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

       city  
0  SQL City

- Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".

- By Reading discription of crime scene report had on 15 janury 2018 there were 2 witenesess

In [17]:
person1 = pd.read_sql_query('''SELECT *
                            FROM person
                            WHERE address_street_name = 'Northwestern Dr'
                            ORDER BY address_number
                            DESC LIMIT 1''',conn)
person1

id            name  license_id  address_number address_street_name  \
0  14887  Morty Schapiro      118009            4919     Northwestern Dr   

         ssn  
0  111564949

In [18]:
person2 = pd.read_sql_query('''SELECT *
                            FROM person
                            WHERE address_street_name = 'Franklin Ave' and name LIKE 'Annabel%'
                            ORDER BY address_number DESC''',conn)
person2

id            name  license_id  address_number address_street_name  \
0  16371  Annabel Miller      490173             103        Franklin Ave   

         ssn  
0  318771143

# Witness Found
- First person is Morty Schapiro which has id 14887
- Second person is Annabel Miller which has id 16371


In [19]:
interview= pd.read_sql_query('''SELECT *
                            FROM interview
                            WHERE person_id = 16371 or person_id = 14887''',conn)
interview.head()

person_id  \
0      14887   
1      16371   

                                                                                                                                                                                                                        transcript  
0  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".  
1                                                                                                            I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

After reading transcript we can say that murder had


*   "Get Fit Now Gym" bag
*   Gold Member of "Get Fit Now Gym" which has id like "48Z"
*   Number of car like "H42W"
*   Murder date january 9th



In [20]:
# checking gold membership and id LIKE '48Z'
# and checking date january 9th
que = pd.read_sql_query('''SELECT a.id , a.person_id, a.name, a.membership_start_date, a.membership_status, b.check_in_date
                        FROM get_fit_now_member AS a
                        INNER JOIN get_fit_now_check_in as b
                        ON a.id = b.membership_id

                        WHERE membership_status = 'gold' and
                        id LIKE '48Z%'
                            ''',conn)
que

id  person_id           name  membership_start_date membership_status  \
0  48Z7A      28819   Joe Germuska               20160305              gold   
1  48Z55      67318  Jeremy Bowers               20160101              gold   

   check_in_date  
0       20180109  
1       20180109

Inner Joinning the person, drivers_license and get_fit_now_member tables

for finding murderer using above clues

In [21]:
que2 = pd.read_sql_query('''SELECT p.id, p.name, p.license_id, p.address_street_name, dl.gender, dl.plate_number, gtn.membership_status
                        FROM person as p
                        INNER JOIN drivers_license as dl
                        ON p.license_id = dl.id
                        INNER JOIN get_fit_now_member as gtn
                        ON p.id = gtn.person_id
                        WHERE plate_number LIKE '%H42W%' and
                        gender = 'male'
                            ''',conn)
que2

id           name  license_id    address_street_name gender  \
0  67318  Jeremy Bowers      423327  Washington Pl, Apt 3A   male   

  plate_number membership_status  
0       0H42W2              gold

Muderer Found!!!

In [ ]:
#verifying murderer
verify = pd.read_sql_query("INSERT INTO solution VALUES (1, 'Jeremy Bowers')", conn)

In [23]:
sol = pd.read_sql_query("SELECT * FROM solution",conn)
sol

user  \
0     0   

                                                                                                                                                                                                                                                                                                                                                                                                value  
0  Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

Finally!!!

murderer found but there is twist, behind murderer there is a master mind

# Finding Master Mind

In [24]:
# After interviewing the murderer we found some clue about master mind
interview= pd.read_sql_query('''SELECT *
                            FROM interview
                            WHERE person_id='67318' ''',conn)
interview.head()

person_id  \
0      67318   

                                                                                                                                                                                                                                           transcript  
0  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n

Clue is-

I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.

 * **Gender - Female**

* **Height - 65 or 67**

* **Hair color - red**

* **Car - Tesla Model s**

* **Attended the SQL Symphony Concert 3 times in December 2017**

In [25]:
drivers_license = pd.read_sql_query('''SELECT *
                                    FROM drivers_license
                                    WHERE gender = 'female' and
                                    hair_color = 'red' and
                                    car_make = 'Tesla' and
                                    car_model = 'Model S' and
                                    height BETWEEN 65 AND 67

                                    ''', conn)
drivers_license.head()

id  age  height eye_color hair_color  gender plate_number car_make  \
0  202298   68      66     green        red  female       500123    Tesla   
1  291182   65      66      blue        red  female       08CM64    Tesla   
2  918773   48      65     black        red  female       917UU3    Tesla   

  car_model  
0   Model S  
1   Model S  
2   Model S

According to clue master mind Attended the SQL Symphony Concert 3 times in December 2017

In [26]:
facebook_event_checkin= pd.read_sql_query('''SELECT *
                                        FROM facebook_event_checkin
                                        WHERE date like '201712%'
                                        ''',conn)
facebook_event_checkin.head()

person_id  event_id  \
0      31811      8542   
1      41421      3799   
2      66493       816   
3      96520      8784   
4      33355      1973   

                                                                 event_name  \
0                                                     -- Herbert Prochnow\n   
1                                      And everywhere this language went,\n   
2  Just because your doctor has a name for your condition doesn't mean he\n   
3    Good advice is something a man gives when he is too old to set a bad\n   
4                                                    He sure is a fun god\n   

       date  
0  20171203  
1  20171206  
2  20171211  
3  20171218  
4  20171205

Inner Joinning person, drivers_license, facebook_event_checkin tables.

considerring above clues

In [27]:
final = pd.read_sql_query('''SELECT p.id,p.name, dl.height, dl.hair_color, dl.gender, dl.car_make, dl.car_model, fec.event_name, fec.date
                        FROM person as p
                        INNER JOIN drivers_license as dl
                        ON p.license_id = dl.id
                        INNER JOIN facebook_event_checkin as fec
                        ON p.id = fec.person_id
                        WHERE gender = 'female' and
                        hair_color = 'red' and
                        car_make = 'Tesla' and
                        car_model = 'Model S' and
                        height BETWEEN 65 AND 67 and
                        date like '201712%'

                                ''',conn)
final

id              name  height hair_color  gender car_make car_model  \
0  99716  Miranda Priestly      66        red  female    Tesla   Model S   
1  99716  Miranda Priestly      66        red  female    Tesla   Model S   
2  99716  Miranda Priestly      66        red  female    Tesla   Model S   

             event_name      date  
0  SQL Symphony Concert  20171206  
1  SQL Symphony Concert  20171212  
2  SQL Symphony Concert  20171229

Master Mind Found!!!!

her name is "Miranda Priestly"

In [ ]:
# Checking the master mind
result = pd.read_sql_query("INSERT INTO solution VALUES (1, 'Miranda Priestly')",conn)
result

Congrats, Master Mind Found.....

In [29]:
result2=pd.read_sql_query("SELECT * FROM solution",conn)
result2

user  \
0     0   

                                                                                                                                                          value  
0  Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!